language: cpp

os: linux

compiler:
  - clang
  - gcc
  
addons:
  apt:
      sources:
          - ubuntu-toolchain-r-test
      packages:
          - gcc-7
          - g++-7

script:
    #Test running script
    make && make test
    #return 0;

    after_script:
    #deploy default Message
    - echo "Finished testing\n Results in "