dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-7
      - clang-5.0
stdlib:
  - libc++
  - stdlibc++

std:
  - c++03
  - c++11
  - c++14
  - c++17
  - c++-latest
  
os:
  -linux

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
 - make 