language: cpp

os: linux

compiler: gcc
    
addons:
  apt:
    sources: &precise_latest_boost_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages: &precise_latest_boost_packages
      - g++-7
      - clang-5.0

stdlib:
  - libc++
  - stdlibc++

std:
  - c++03
  - c++11
  - c++14
  - c++17
  - c++-latest
  
before_script:
  - mkdir -p build
  - cd build
  - cmake

script:
 - make 