language: cpp

compiler:
  - gcc
  - clang
os:
  -linux
addons: 
  apt:
    sources:
    - ubuntu-toolchain-r-test                - llvm-toolchain-precise-3.8
    - llvm-toolchain-precise-3.8
    packages:
    - gcc-7
    - g++-7
    - clang-3.8
before_script:
  - mkdir build
  - cd build
  - cmake ..
install:
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
script: 
  -make
  -make test
